[[rtmidi]]
arch = "aarch64"
git-tree-sha1 = "1238303144001966d0950b4a08449feb261cbd13"
os = "macos"

    [[rtmidi.download]]
    sha256 = "c9ef43beb77fb334a737fc6c6c3a6bd6c2afbda4d42670c898b2db287601a654"
    url = "https://github.com/anandijain/rtmidi/releases/download/rtmidi-v5.0.0+0/rtmidi.v5.0.0.aarch64-apple-darwin.tar.gz"
[[rtmidi]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "aee0d27a74f75e76b7bdd7d53dda54d481964bc8"
libc = "glibc"
os = "linux"

    [[rtmidi.download]]
    sha256 = "6a1d6844778bd8370b41b952b21773374896dc50fa21e86c118ac9524e49a74f"
    url = "https://github.com/anandijain/rtmidi/releases/download/rtmidi-v5.0.0+0/rtmidi.v5.0.0.aarch64-linux-gnu-cxx03.tar.gz"
[[rtmidi]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "37ef4a3e1806e3c27b6b87878cd8c273b455641e"
libc = "glibc"
os = "linux"

    [[rtmidi.download]]
    sha256 = "63e33de996e5e0a095249dd8e54fde449a9edd8e7cb831c1a8cdd1f9ce44a129"
    url = "https://github.com/anandijain/rtmidi/releases/download/rtmidi-v5.0.0+0/rtmidi.v5.0.0.aarch64-linux-gnu-cxx11.tar.gz"
[[rtmidi]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "00b1ec715fdb7c450195a9a4c68e47b72cfb7d46"
libc = "glibc"
os = "linux"

    [[rtmidi.download]]
    sha256 = "6aada7994b1857456fd9f25df9d62d964ca2d50a4e34f2c6dbdd994066904c02"
    url = "https://github.com/anandijain/rtmidi/releases/download/rtmidi-v5.0.0+0/rtmidi.v5.0.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[rtmidi]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "17e273c741720a47e6d8f17657ba88555a0f923c"
libc = "glibc"
os = "linux"

    [[rtmidi.download]]
    sha256 = "7d3011016c8cfa62a72b4732eb4826f982982a191acb246b9bbda2c140c39089"
    url = "https://github.com/anandijain/rtmidi/releases/download/rtmidi-v5.0.0+0/rtmidi.v5.0.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[rtmidi]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "99d2921be8a0ee87ceed2e287791665fab371a2e"
libc = "glibc"
os = "linux"

    [[rtmidi.download]]
    sha256 = "1bcb7921e6e5c28a6b2225090adf20a183bd10654bbf3adeb429bebf858d7b9c"
    url = "https://github.com/anandijain/rtmidi/releases/download/rtmidi-v5.0.0+0/rtmidi.v5.0.0.i686-linux-gnu-cxx03.tar.gz"
[[rtmidi]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9b7ec40eaa6359410a6a2bd732f479b5e303552d"
libc = "glibc"
os = "linux"

    [[rtmidi.download]]
    sha256 = "a74c0268574ba5ba2425f3abe7cbf8c7d83aee8774f0efbd9d297691995b463d"
    url = "https://github.com/anandijain/rtmidi/releases/download/rtmidi-v5.0.0+0/rtmidi.v5.0.0.i686-linux-gnu-cxx11.tar.gz"
[[rtmidi]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ba74e6cbd063b9011e8c632d2231a952e0ec7a28"
os = "windows"

    [[rtmidi.download]]
    sha256 = "196716079d01b692a9699694bd04b570492e65a41d9381e066de6d414c61c402"
    url = "https://github.com/anandijain/rtmidi/releases/download/rtmidi-v5.0.0+0/rtmidi.v5.0.0.i686-w64-mingw32-cxx03.tar.gz"
[[rtmidi]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4daed3a8d795fccd2336cb11b0066e9491b3a797"
os = "windows"

    [[rtmidi.download]]
    sha256 = "e1a8d01542b340aa1e3f293e0b4a50c2509715dcece9fa296dbe3fec0a45303c"
    url = "https://github.com/anandijain/rtmidi/releases/download/rtmidi-v5.0.0+0/rtmidi.v5.0.0.i686-w64-mingw32-cxx11.tar.gz"
[[rtmidi]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "27643a4a5ae5a9b0901487cf84bcba29fd75d67e"
libc = "glibc"
os = "linux"

    [[rtmidi.download]]
    sha256 = "2ff9cdafefe7d9b5705cee59c377454e141157dbf47ba3b48fda38e422ae1207"
    url = "https://github.com/anandijain/rtmidi/releases/download/rtmidi-v5.0.0+0/rtmidi.v5.0.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[rtmidi]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ed2b6fc609ffe0b8aa391fe7bd201f0fd32e8cc7"
libc = "glibc"
os = "linux"

    [[rtmidi.download]]
    sha256 = "d497b1af49c5e510fa42561e9cba533dc9df2afcb946cf6ff3409d18b601d143"
    url = "https://github.com/anandijain/rtmidi/releases/download/rtmidi-v5.0.0+0/rtmidi.v5.0.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[rtmidi]]
arch = "x86_64"
git-tree-sha1 = "ae8530fe207b4443b6006019fc611e4f51a6cd16"
os = "macos"

    [[rtmidi.download]]
    sha256 = "969be78ea813a7fb728c0de5024b44cc6b0eff7a172aa98d7f4614dfd65e0300"
    url = "https://github.com/anandijain/rtmidi/releases/download/rtmidi-v5.0.0+0/rtmidi.v5.0.0.x86_64-apple-darwin.tar.gz"
[[rtmidi]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fe58e0ce3c031e74862d1c2cfc9e26b330cbeccd"
libc = "glibc"
os = "linux"

    [[rtmidi.download]]
    sha256 = "749c68edc6e0df7699a58df30573e341abd1a1d8611de377614d21065bb37806"
    url = "https://github.com/anandijain/rtmidi/releases/download/rtmidi-v5.0.0+0/rtmidi.v5.0.0.x86_64-linux-gnu-cxx03.tar.gz"
[[rtmidi]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ffbd07707d2cc67b9f857cce656c9947a685dc1c"
libc = "glibc"
os = "linux"

    [[rtmidi.download]]
    sha256 = "13916fd803fd6f6a776cf0618366c77b1a8f9d636943563b87d620d30860bea5"
    url = "https://github.com/anandijain/rtmidi/releases/download/rtmidi-v5.0.0+0/rtmidi.v5.0.0.x86_64-linux-gnu-cxx11.tar.gz"
[[rtmidi]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "76ba812ee7cde86aaecf39ef3a866fb890234ef3"
os = "windows"

    [[rtmidi.download]]
    sha256 = "fac115f998a9a02eefa8189d88a5e5ecff20714af8330df260d9d8fcf8f9b0ff"
    url = "https://github.com/anandijain/rtmidi/releases/download/rtmidi-v5.0.0+0/rtmidi.v5.0.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[rtmidi]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e9510b69a8b0ae95f086c00b611ee18cefeaeee6"
os = "windows"

    [[rtmidi.download]]
    sha256 = "fed15cfb67148c12924715cfdd443164beff2feb04f9bb5df58a7f5c6de825b4"
    url = "https://github.com/anandijain/rtmidi/releases/download/rtmidi-v5.0.0+0/rtmidi.v5.0.0.x86_64-w64-mingw32-cxx11.tar.gz"
