[[rtmidi]]
arch = "aarch64"
git-tree-sha1 = "cfaaf4df489d45f28b3db800d2e961bba4b1c949"
os = "macos"

    [[rtmidi.download]]
    sha256 = "3ee0059ae0184f6df6006756219bf7b0d2785d32a642ac10758fedd11672af26"
    url = "https://github.com/anandijain/rtmidi_jll.jl/releases/download/rtmidi-v5.0.0%2B0/rtmidi.v5.0.0.aarch64-apple-darwin.tar.gz"
[[rtmidi]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "33d995d2f927225056400d08e2e02a2142b4ed17"
libc = "glibc"
os = "linux"

    [[rtmidi.download]]
    sha256 = "0bfa7dbcc2e0f0b0db3230e40bff8eebbdfb92c893a6037efea860eeb23233bb"
    url = "https://github.com/anandijain/rtmidi_jll.jl/releases/download/rtmidi-v5.0.0+0/rtmidi.v5.0.0.aarch64-linux-gnu-cxx03.tar.gz"
[[rtmidi]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0898f0ea3707687e3d5ac3649ca06e6b165ee751"
libc = "glibc"
os = "linux"

    [[rtmidi.download]]
    sha256 = "a1e1d6248c64a2b63dfbe284dbd5be0d45c487827f9db2799f5f4a8f6d3675a2"
    url = "https://github.com/anandijain/rtmidi_jll.jl/releases/download/rtmidi-v5.0.0+0/rtmidi.v5.0.0.aarch64-linux-gnu-cxx11.tar.gz"
[[rtmidi]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f3fbc0b9e8811d369b11e04ec3c77b0eb867e997"
libc = "glibc"
os = "linux"

    [[rtmidi.download]]
    sha256 = "c53eb3877a9570fc5a3f798472da90d044de6f3e0d71495fcbe43650e2ae9640"
    url = "https://github.com/anandijain/rtmidi_jll.jl/releases/download/rtmidi-v5.0.0+0/rtmidi.v5.0.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[rtmidi]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7af56654e713dcba54be96577c11384fee828587"
libc = "glibc"
os = "linux"

    [[rtmidi.download]]
    sha256 = "349e25cd47605b0e96602591e416093e434dff5b01fc278ef62dcd97f5ec4802"
    url = "https://github.com/anandijain/rtmidi_jll.jl/releases/download/rtmidi-v5.0.0+0/rtmidi.v5.0.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[rtmidi]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4cbd069f76d6ec98701d46663e8b513d6878569c"
libc = "glibc"
os = "linux"

    [[rtmidi.download]]
    sha256 = "01114ac355526c059e92cf4eb6bb59df2a7fb69c75d1197ed18a6fe0df06c424"
    url = "https://github.com/anandijain/rtmidi_jll.jl/releases/download/rtmidi-v5.0.0+0/rtmidi.v5.0.0.i686-linux-gnu-cxx03.tar.gz"
[[rtmidi]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fae70f414e142a913f8ff1b7dc6732a85cb43271"
libc = "glibc"
os = "linux"

    [[rtmidi.download]]
    sha256 = "4904c3a688074bb695405e026df69ae6a024306fcdf15d0844bdbe24439aee4d"
    url = "https://github.com/anandijain/rtmidi_jll.jl/releases/download/rtmidi-v5.0.0+0/rtmidi.v5.0.0.i686-linux-gnu-cxx11.tar.gz"
[[rtmidi]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c9349813bc2292f91aec3ef5813d49319089a0cd"
os = "windows"

    [[rtmidi.download]]
    sha256 = "538d60c1908f04b89d99baad8980b5748eb3f3f4699e77e4253c8bea338da51e"
    url = "https://github.com/anandijain/rtmidi_jll.jl/releases/download/rtmidi-v5.0.0+0/rtmidi.v5.0.0.i686-w64-mingw32-cxx03.tar.gz"
[[rtmidi]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "97e7e10404d0074700b746469b15c0f89ecd40e5"
os = "windows"

    [[rtmidi.download]]
    sha256 = "241b6cb732c25c6c25edbba809954bf4d0723f43bb7487e8b4b90d37ba18ed7a"
    url = "https://github.com/anandijain/rtmidi_jll.jl/releases/download/rtmidi-v5.0.0+0/rtmidi.v5.0.0.i686-w64-mingw32-cxx11.tar.gz"
[[rtmidi]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "366b081b70dcbb0aae129609e31d4a334588f0c1"
libc = "glibc"
os = "linux"

    [[rtmidi.download]]
    sha256 = "864bf9ce2fe3531e289307d5efb6250b48033538803437b7e436a8f936698ed3"
    url = "https://github.com/anandijain/rtmidi_jll.jl/releases/download/rtmidi-v5.0.0+0/rtmidi.v5.0.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[rtmidi]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e306d19d84a6cafbff375556f1c61e32e0dac94e"
libc = "glibc"
os = "linux"

    [[rtmidi.download]]
    sha256 = "357c88ea2a6cc335367f944d55abc2794a7bce478a6db0ca63bcc24f4c04d7de"
    url = "https://github.com/anandijain/rtmidi_jll.jl/releases/download/rtmidi-v5.0.0+0/rtmidi.v5.0.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[rtmidi]]
arch = "x86_64"
git-tree-sha1 = "9036dfda7927e88f6b3eaf4bba02327961404833"
os = "macos"

    [[rtmidi.download]]
    sha256 = "34253f61d00c24e00dcf95fe4e7901d98ba6434ce8ab03b963d8834067cfe65e"
    url = "https://github.com/anandijain/rtmidi_jll.jl/releases/download/rtmidi-v5.0.0+0/rtmidi.v5.0.0.x86_64-apple-darwin.tar.gz"
[[rtmidi]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "06369e70cf2f2e4bf1c59af7c83c8f369b795a4b"
libc = "glibc"
os = "linux"

    [[rtmidi.download]]
    sha256 = "44464c17d3282e02e1c288f57457fffecedebf3f6107c2ac37b89f3a0feeb6ea"
    url = "https://github.com/anandijain/rtmidi_jll.jl/releases/download/rtmidi-v5.0.0+0/rtmidi.v5.0.0.x86_64-linux-gnu-cxx03.tar.gz"
[[rtmidi]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a80419515e8a7b366a99c7c60ce56f39b8be5318"
libc = "glibc"
os = "linux"

    [[rtmidi.download]]
    sha256 = "f641c6c9cf86a001f5c24fc0c4a1c82e850e5cd6ad25d4187ddcccd5b5ab4ca4"
    url = "https://github.com/anandijain/rtmidi_jll.jl/releases/download/rtmidi-v5.0.0+0/rtmidi.v5.0.0.x86_64-linux-gnu-cxx11.tar.gz"
[[rtmidi]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2cc90c09b38fb82d6b6c37d4266510110d306686"
os = "windows"

    [[rtmidi.download]]
    sha256 = "107f029c9eb0034f177e984c65e26ada0ee13fe004e9ef7a344a52a12946971a"
    url = "https://github.com/anandijain/rtmidi_jll.jl/releases/download/rtmidi-v5.0.0+0/rtmidi.v5.0.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[rtmidi]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2ebcf2c60f3edf0c158a9d7a9244a1874177e70f"
os = "windows"

    [[rtmidi.download]]
    sha256 = "d8f25b892b202ddd76781506f50b8fdebb23c3c39f5728edd2a4c528ec715e4a"
    url = "https://github.com/anandijain/rtmidi_jll.jl/releases/download/rtmidi-v5.0.0+0/rtmidi.v5.0.0.x86_64-w64-mingw32-cxx11.tar.gz"
