[[rtmidi]]
arch = "aarch64"
git-tree-sha1 = "cfaaf4df489d45f28b3db800d2e961bba4b1c949"
os = "macos"

    [[rtmidi.download]]
    sha256 = "38059b2ab3939cf9651f5abf9aeb489645489ee31dad998b4f538137f161fef6"
    url = "https://github.com/anandijain/rtmidi_jll.jl/releases/download/rtmidi-v5.0.0+0/rtmidi.v5.0.0.aarch64-apple-darwin.tar.gz"
[[rtmidi]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "33d995d2f927225056400d08e2e02a2142b4ed17"
libc = "glibc"
os = "linux"

    [[rtmidi.download]]
    sha256 = "3f552ee87153e34e80e9996851b25e163f7bc5f637805ba0e91bc33f07d72d24"
    url = "https://github.com/anandijain/rtmidi_jll.jl/releases/download/rtmidi-v5.0.0+0/rtmidi.v5.0.0.aarch64-linux-gnu-cxx03.tar.gz"
[[rtmidi]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0898f0ea3707687e3d5ac3649ca06e6b165ee751"
libc = "glibc"
os = "linux"

    [[rtmidi.download]]
    sha256 = "4e694721bf6ef25c91378b93bb9aa4b3f4d0ea561d3a5201db9c71bb0e868572"
    url = "https://github.com/anandijain/rtmidi_jll.jl/releases/download/rtmidi-v5.0.0+0/rtmidi.v5.0.0.aarch64-linux-gnu-cxx11.tar.gz"
[[rtmidi]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f3fbc0b9e8811d369b11e04ec3c77b0eb867e997"
libc = "glibc"
os = "linux"

    [[rtmidi.download]]
    sha256 = "87d4ed0175b00a5502b4f625ed5c318fae79c50e2e71f4ec387ffe48dd2544d2"
    url = "https://github.com/anandijain/rtmidi_jll.jl/releases/download/rtmidi-v5.0.0+0/rtmidi.v5.0.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[rtmidi]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7af56654e713dcba54be96577c11384fee828587"
libc = "glibc"
os = "linux"

    [[rtmidi.download]]
    sha256 = "d0cb8af7de1c45d666efdf480532d67e2b7c369ba28b07879a0f0ca41081c39e"
    url = "https://github.com/anandijain/rtmidi_jll.jl/releases/download/rtmidi-v5.0.0+0/rtmidi.v5.0.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[rtmidi]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4cbd069f76d6ec98701d46663e8b513d6878569c"
libc = "glibc"
os = "linux"

    [[rtmidi.download]]
    sha256 = "1025fd91f67c317a2428ee7f7f9c45dc3fb702e36f74e4420927f3375b4d1662"
    url = "https://github.com/anandijain/rtmidi_jll.jl/releases/download/rtmidi-v5.0.0+0/rtmidi.v5.0.0.i686-linux-gnu-cxx03.tar.gz"
[[rtmidi]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fae70f414e142a913f8ff1b7dc6732a85cb43271"
libc = "glibc"
os = "linux"

    [[rtmidi.download]]
    sha256 = "69a719fe98af11ec075255b312f7f00e37fc0ad585f807328ef44ea9e63c1db1"
    url = "https://github.com/anandijain/rtmidi_jll.jl/releases/download/rtmidi-v5.0.0+0/rtmidi.v5.0.0.i686-linux-gnu-cxx11.tar.gz"
[[rtmidi]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3241ec747e2125aa6356dabbfde5c9a832133539"
os = "windows"

    [[rtmidi.download]]
    sha256 = "35e5ea2b1118d658c2e788594b4636065dbda04299839ae3229191acdfbfe849"
    url = "https://github.com/anandijain/rtmidi_jll.jl/releases/download/rtmidi-v5.0.0+0/rtmidi.v5.0.0.i686-w64-mingw32-cxx03.tar.gz"
[[rtmidi]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5e1724746a3b9b4b479b3c95be8c8c6716d5c0a3"
os = "windows"

    [[rtmidi.download]]
    sha256 = "f6a029eaf42e733e4b3e0946cbb4ba3bc43a5266b54937a6c004fb1a2df9945a"
    url = "https://github.com/anandijain/rtmidi_jll.jl/releases/download/rtmidi-v5.0.0+0/rtmidi.v5.0.0.i686-w64-mingw32-cxx11.tar.gz"
[[rtmidi]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "366b081b70dcbb0aae129609e31d4a334588f0c1"
libc = "glibc"
os = "linux"

    [[rtmidi.download]]
    sha256 = "d2cfdc0160e9e5d83cdd9015139b3e4e8b18fc824bebad3b4913512c5742039d"
    url = "https://github.com/anandijain/rtmidi_jll.jl/releases/download/rtmidi-v5.0.0+0/rtmidi.v5.0.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[rtmidi]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e306d19d84a6cafbff375556f1c61e32e0dac94e"
libc = "glibc"
os = "linux"

    [[rtmidi.download]]
    sha256 = "13fa76de65b716c99cecd4b5db3d600a6ff212e11ba095234b78d1c9bef83746"
    url = "https://github.com/anandijain/rtmidi_jll.jl/releases/download/rtmidi-v5.0.0+0/rtmidi.v5.0.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[rtmidi]]
arch = "x86_64"
git-tree-sha1 = "9036dfda7927e88f6b3eaf4bba02327961404833"
os = "macos"

    [[rtmidi.download]]
    sha256 = "b40d78976bbaa6de0c9204e505cd0674a090d35f0af07baaf18f698a352b1983"
    url = "https://github.com/anandijain/rtmidi_jll.jl/releases/download/rtmidi-v5.0.0+0/rtmidi.v5.0.0.x86_64-apple-darwin.tar.gz"
[[rtmidi]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "06369e70cf2f2e4bf1c59af7c83c8f369b795a4b"
libc = "glibc"
os = "linux"

    [[rtmidi.download]]
    sha256 = "3d4a59e9a5baf7d233471807558b724f1025524122fe39fbf0bfac07d9bd71f8"
    url = "https://github.com/anandijain/rtmidi_jll.jl/releases/download/rtmidi-v5.0.0+0/rtmidi.v5.0.0.x86_64-linux-gnu-cxx03.tar.gz"
[[rtmidi]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a80419515e8a7b366a99c7c60ce56f39b8be5318"
libc = "glibc"
os = "linux"

    [[rtmidi.download]]
    sha256 = "6ee7aadb06ee8d57b9fc99c57e9f88f20ea7df62c77f7e5505b025b73fe77f3e"
    url = "https://github.com/anandijain/rtmidi_jll.jl/releases/download/rtmidi-v5.0.0+0/rtmidi.v5.0.0.x86_64-linux-gnu-cxx11.tar.gz"
[[rtmidi]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d80ef29cfdc3c7b631dd08057ee631cb52d06fc7"
os = "windows"

    [[rtmidi.download]]
    sha256 = "6f5554fdc8d5a4882cd23d70e6035617babaa312c0768741ac1464b99fd5c061"
    url = "https://github.com/anandijain/rtmidi_jll.jl/releases/download/rtmidi-v5.0.0+0/rtmidi.v5.0.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[rtmidi]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0ce6d37a00a6eb12bc4c8037b329a214562243ae"
os = "windows"

    [[rtmidi.download]]
    sha256 = "e808fc54fc8f32903b0c167b3aa1e165108287b38d520cd388d4087a2e1726fb"
    url = "https://github.com/anandijain/rtmidi_jll.jl/releases/download/rtmidi-v5.0.0+0/rtmidi.v5.0.0.x86_64-w64-mingw32-cxx11.tar.gz"
